
import "./globals.css";
import { SidebarProvaider } from '@/app/Contaxt/contax'

export const metadata = {
  title: "Fhoto Modal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body>
          {children}
          </body>
    </html>
  );
}
